### ISSUE TITLE
Write the readme

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#102]
## Description 📹

**Write a readme. You can take some ideas from there: https://github.com/lfglabs-dev/api.starknet.quest/blob/testnet/README.md**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] Add each section of the readme, such as: How to install it
- [ ] How to run it
- [ ] Troubleshoot section

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by NueloSE** [comment]
@Marchand-Nicolas can i be assigned this issue ETA <= 24hrs

**Comment by mayasimi** [comment]
@Marchand-Nicolas can i work on this

**Comment by CollinsC1O** [comment]
Hi @Marchand-Nicolas I'm a front-end and a blockchain developer. I will love to work on this

**Comment by SudiptaPaul-31** [comment]
Can I attempt this issue?

**Comment by Emmanex01** [comment]
Hi,
Could I try solving this?

**Comment by Benjtalkshow** [comment]
I’d love to work on this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

My ETA is 48hrs.

**Comment by josephchimebuka** [comment]
May I be assigned to this?

**Comment by 0xdevcollins** [comment]
Would love to tackle this!

**Comment by Aditya-040** [comment]
Is it okay if I take this?

**Comment by mimisavage** [comment]
Is this issue still available?

**Comment by pheobeayo** [comment]
Can I tackle this one?

I will create my first PR in few hours

**Comment by Kritto** [comment]
I will create a comprehensive README based on the structure and content from the provided example, tailoring it to the specific needs of the project. 

The README will include sections on installation, running the project, and troubleshooting common issues, ensuring that new users can quickly get up and running with clear instructions.

Assign me this task so get started crafting a detailed and user-friendly README that makes onboarding a smooth process and troubleshooting effortless immediately.

Best regards

**Comment by petersdt** [comment]
@Marchand-Nicolas I’d like to help with this.

i will deliver a timely and easy to understand README.md file to make introduction and navigation through the project easy to understand for both first time and returning users . kindly assign me and expect deliverable in 5hrs max

**Comment by NueloSE** [comment]
Can I handle this task?

**Comment by hossamanany** [comment]
I’d like to help with this.

**Comment by suhas-sensei** [comment]
Can I be assigned to this? i would like to contribute.

**Comment by Yunusabdul38** [comment]
I’d like to work on this.
and make sure it meets the requirements

**Comment by Benjtalkshow** [comment]
@Marchand-Nicolas 
I wanna let you know that i am still working on this. Thanks
