### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#103]
## Description 📹

**Fix the warnings when using `cargo build`, such as “use of deprecated method” warnings.**  
Several warnings are being raised during the build process when using `cargo build`. These warnings may include the use of deprecated methods or features. This issue aims to resolve these warnings to ensure a clean build process.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	- [ ] Identify all warnings generated by `cargo build`.
	- [ ] Locate the source of each warning in the codebase.
	- [ ] Update the code to use recommended or non-deprecated alternatives.
	- [ ] If you think some warnings can be ignored, such as the async_warning function that is currently unused, but that we'll probably use in the future, you can leave them.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Resolved warnings during cargo build"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by anonfedora** [comment]
I'm a fullstack Blockchain developer. Will resolve these warnings to ensure a clean build process by reviewing and upgrading deprecated methods as required.

**Comment by OWK50GA** [comment]
Is it okay if I tackle this?
I'm a Cairo Smart Contract Developer

**Comment by Emmanex01** [comment]
Is it okay if I tackle this?

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task. ETA 48hrs.

**Comment by josephchimebuka** [comment]
Would love to tackle this!

**Comment by 0xdevcollins** [comment]
Would love to tackle this!

**Comment by mimisavage** [comment]
Can I attempt this issue?

**Comment by pheobeayo** [comment]
Can I start working on this?
I will create my first PR in a day.

**Comment by hossamanany** [comment]
I’m interested in this one.

**Comment by suhas-sensei** [comment]
I’d like to work on this.

**Comment by ooochoche** [comment]
I'd like to take this issue.

**Comment by ooochoche** [comment]
I've gone through the description and the requirements and can fix warning to meet the proposed actions if assigned the task

**Comment by pheobeayo** [comment]
Will get right on it
