### ISSUE TITLE
Implement WatchTower

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#104]
## Description 📹

**Implement WatchTower as described in the repository [api.starknet.quest](https://github.com/lfglabs-dev/api.starknet.quest).**  
This involves setting up WatchTower for monitoring and handling operations as described in the linked repository's implementation.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - [ ] Review the [api.starknet.quest implementation](https://github.com/lfglabs-dev/api.starknet.quest) for the WatchTower setup.  
   - [ ] Implement similar functionality tailored to the current repository's structure and requirements.
   - [ ] Ensure necessary dependencies are added and documented.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

   ```bash
   git commit -m "Fix: Implement WatchTower functionality as per api.starknet.quest"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by 0xdevcollins** [comment]
Can I try solving this issue?

**Comment by mimisavage** [comment]
May I take care of this?

**Comment by bloomingpeach** [comment]
Could I try solving this? I have experience in various Rust projects: reth, foundry-rs, starknet-foundry, near-sdk-rs, ibc-rs.

**Comment by hoank101** [comment]
i can handler this

**Comment by htiennv** [comment]
Hi @Marchand-Nicolas, i would like to take this issue. I have many years for contribute to Rust open source projects. Thanks!

**Comment by TropicalDog17** [comment]
Could I try solving this? I have experience in various open source Rust projects

**Comment by suhas-sensei** [comment]
Can I start working on this? i have experience in rust and have worked with the repo previously. draft pr in 24 hrs

**Comment by TropicalDog17** [comment]
Thanks for the assignment, I will try to put up a draft PR early next week @Marchand-Nicolas
