### ISSUE TITLE
Add tests for extract_prefix_and_root

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#105]
## Description 📹

**Add tests for the `extract_prefix_and_root` function located in `src/utils.rs`.**  
Ensure the function's behavior is thoroughly validated under various scenarios, including edge cases.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
   Add unit tests for the `extract_prefix_and_root` function. Place the tests in the appropriate test module within `src/utils.rs` or a dedicated test file.  
   
   **Test cases to include**:
   - [ ] Valid inputs with distinct prefix and root combinations.
   - [ ] Inputs with no prefix or root to test edge cases.
   - [ ] Empty string input.
   - [ ] Unexpected formats or invalid data.
   - [ ] Any other cases relevant to the function's specification.

   Example (to be expanded upon):

   ```rust
   #[cfg(test)]
   mod tests {
       use super::*;

       #[test]
       fn test_extract_prefix_and_root_valid_input() {
           let input = ...;
           let (prefix, root) = extract_prefix_and_root(input).unwrap();
           assert_eq!(prefix, ...;
           assert_eq!(root, ...);
       }

       // Add more cases here
   }
   ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Test: Add unit tests for extract_prefix_and_root function"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by psychemist** [comment]
Hi @Marchand-Nicolas I would love to work on this issue. I have experience with testing codebases for maximum efficacy

**Comment by NueloSE** [comment]
hi @Marchand-Nicolas can i be assign the above issue

**Comment by Emmanex01** [comment]
Could I be assigned to this?

**Comment by josephchimebuka** [comment]
I’d like to resolve this.

**Comment by 0xdevcollins** [comment]
Is it okay if I tackle this?

**Comment by mimisavage** [comment]
I’d like to help with this.

**Comment by petersdt** [comment]
I would create a test file for testing purpose so as not to make the utilis.rs file too lengthy and mostly because of SoC.

I will ensure i cover all the check cases listed above. ETA <= 24hrs

Could I take over this issue?

**Comment by Kritto** [comment]
I will add thorough unit tests for the `extract_prefix_and_root` function, covering various scenarios such as valid inputs, edge cases like missing prefixes or roots, empty strings, and invalid formats. 

These tests will ensure the function behaves correctly under all conditions, preventing future issues and ensuring stability.

Assign me this task, let's strenghthen the reliability of `extract_prefix_and_root` by implementing comprehensive tests that cover all edge cases and ensure consistent behavior.

**Comment by mayasimi** [comment]
Can I contribute to this one?

**Comment by NueloSE** [comment]
I’d like to resolve this.

**Comment by suhas-sensei** [comment]
Can I attempt this issue? I have the required experience and would be more than happy to contribute here.

**Comment by ooochoche** [comment]
I've gone through the description and the requirements and I can write the test for the required function within the timeframe
