### ISSUE TITLE
New route: get_expiring_domains

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#109]
## Description 📹

**Add an endpoint called `get_expiring_domains` to return all domains that will expire in less than a week.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

- [ ] Add a new route in the application to handle `GET /get_expiring_domains`.
- [ ] Create a function to query the `domains` collection. The query should:
  - Filter documents where:
    - `_cursor.to` is `null`.
    - `expiry` is less than the current timestamp plus one week.
  - Return an array of objects in the following format:
    ```json
    {
      "addr": "0x",
      "domain": "ben.stark"
    }
    ```
- [ ] Ensure the function retrieves the required fields (`legacy_address` as `addr`, and `domain`).

Example Code Snippet:

```rust
// Pseudocode for database query
let current_time = get_current_timestamp();
let one_week_later = current_time + 604800; // 7 days in seconds

let expiring_domains = domains_collection.find(
    {
        "expiry": { "$lt": one_week_later },
        "_cursor.to": null
    },
    {
        "projection": { "domain": 1, "legacy_address": 1 }
    }
);

let response = expiring_domains.map(|doc| {
    {
        "addr": doc.legacy_address,
        "domain": doc.domain,
    }
});

return response;
```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Add endpoint for fetching domains expiring in less than a week"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by snehaa-eth** [comment]
can i take up thi sissue?i have fullsatck  experience and worked on starkent other repo too

**Comment by Benjtalkshow** [comment]
Can I jump on this task?

**Comment by Michaelkingsdev** [comment]
I’d like to help with this.

**Comment by Emmanex01** [comment]
Could I take on this issue?

**Comment by josephchimebuka** [comment]
I’d like to resolve this.

**Comment by Kritto** [comment]
Hi, I am a software and devops engineer

I will add a new endpoint, get_expiring_domains, to retrieve all domains expiring within the next week. This will involve creating a new route, querying the domains collection with the appropriate filters, and returning the results in the specified format. 

After implementing the changes, I will ensure the functionality is intact by running tests and submit the changes with a clear commit message.

Assign me so I can get started with implementing the get_expiring_domains endpoint and ensure seamless functionality for querying expiring domains.

**Comment by Aditya-040** [comment]
I'd love to give this a go.

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by suhas-sensei** [comment]
i Would love to tackle this one. I will create the get_expiring_domains endpoint with optimized queries to filter domains expiring in a week, ensuring efficiency and minimal database load. Fully tested for seamless functionality.
Draft pr in 24hrs

**Comment by htiennv** [comment]
I would like to take this issue. I have many years for contribute to Rust open source projects. Thanks!
