### ISSUE TITLE
Reinforce the WatchTower implementation 

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#121]
## Description 📹

**Replace println & eprintln by WatchTower (our own logger) as done in src/main.rs**
It looks like that:
```rs
    logger.info(format!(
        "id_server: starting v{}",
        env!("CARGO_PKG_VERSION")
    ));
```
(Don't forget to also use logger.warning & logger.severe when appropriate)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] Use the global search tool provided by your IDE to find all occurences of println and replace them, if possible, by our logger

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by AkintolaRichard** [comment]
Could I try solving this?

**Comment by Crosstons** [comment]
Hey, I can work on this

**Comment by mimisavage** [comment]
May I be assigned to this?

**Comment by emarc99** [comment]
I would love to take this issue. It is quite straight forward.
I have my development environment set up for testing here: https://emarc.hashnode.dev/starknet-development-with-docker-a-streamlined-setup-for-cairo-builders

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You
