### ISSUE TITLE
Add tests to the `clean_string` function in `src/utils.rs`.

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#123]
## Description 📹

**Add tests to the `clean_string` function in `src/utils.rs`.**

The `clean_string` function removes null characters (`\0`) from a string. Add a variety of tests to ensure the function behaves as expected, including edge cases and common usage scenarios.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   Add the following tests to `src/tests/utils.rs`:

   ```rust
   #[cfg(test)]
   mod clean_string {
       use super::*;

       #[test]
       fn test_clean_string_no_nulls() {
           let input = "Hello, world!";
           let result = clean_string(input);
           assert_eq!(result, "Hello, world!");
       }

       #[test]
       fn test_clean_string_with_nulls() {
           let input = "Hello\0, world\0!";
           let result = clean_string(input);
           assert_eq!(result, "Hello, world!");
       }

       #[test]
       fn test_clean_string_only_nulls() {
           let input = "\0\0\0";
           let result = clean_string(input);
           assert_eq!(result, "");
       }

       #[test]
       fn test_clean_string_empty_string() {
           let input = "";
           let result = clean_string(input);
           assert_eq!(result, "");
       }

       #[test]
       fn test_clean_string_unicode_chars() {
           let input = "Hell\0o 🌍\0!";
           let result = clean_string(input);
           assert_eq!(result, "Hello 🌍!");
       }
   }
   ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Add tests for clean_string function"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by aurlic** [comment]
Hey I would be thrilled to work on this issue and contribute to this project !

**Comment by Crosstons** [comment]
Hey, I can work on this

**Comment by mimisavage** [comment]
May I take this issue on?

**Comment by 847850277** [comment]
Can I try solving this issue?

**Comment by emarc99** [comment]
Can I take this issue? Seems quite straight forward.
I have my development environment set up for testing here: https://emarc.hashnode.dev/starknet-development-with-docker-a-streamlined-setup-for-cairo-builders

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by RajeshRk18** [comment]
I will take up this issue! I will add the tests, run them locally before pushing it.

ETA: 3 hours
