### ISSUE TITLE
Add tests to the `parse_image_url` function in `src/utils.rs`

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.id#124]
## Description 📹

**Add tests to the `parse_image_url` function in `src/utils.rs`.**

The `parse_image_url` function replaces the `ipfs://` prefix in a URL with a configurable IPFS gateway URL or returns the original URL unchanged. Add tests to verify its behavior with various inputs and configurations.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   Add the following tests to `src/tests/utils.rs`:

   ```rust
   #[cfg(test)]
   mod parse_image_url {
       use super::*;
       use crate::config::Config;

       #[test]
       fn test_parse_image_url_with_ipfs() {
           let config = Config {
               variables: Variables {
                   ipfs_gateway: "https://ipfs.io/ipfs/".to_string(),
               },
           };
           let input_url = "ipfs://examplehash";
           let expected_output = "https://ipfs.io/ipfs/examplehash";
           let result = parse_image_url(&config, input_url);
           assert_eq!(result, expected_output);
       }

       #[test]
       fn test_parse_image_url_without_ipfs() {
           let config = Config {
               variables: Variables {
                   ipfs_gateway: "https://ipfs.io/ipfs/".to_string(),
               },
           };
           let input_url = "https://example.com/image.png";
           let expected_output = "https://example.com/image.png";
           let result = parse_image_url(&config, input_url);
           assert_eq!(result, expected_output);
       }

       #[test]
       fn test_parse_image_url_empty_url() {
           let config = Config {
               variables: Variables {
                   ipfs_gateway: "https://ipfs.io/ipfs/".to_string(),
               },
           };
           let input_url = "";
           let expected_output = "";
           let result = parse_image_url(&config, input_url);
           assert_eq!(result, expected_output);
       }

       #[test]
       fn test_parse_image_url_custom_ipfs_gateway() {
           let config = Config {
               variables: Variables {
                   ipfs_gateway: "https://custom-ipfs.gateway/".to_string(),
               },
           };
           let input_url = "ipfs://examplehash";
           let expected_output = "https://custom-ipfs.gateway/examplehash";
           let result = parse_image_url(&config, input_url);
           assert_eq!(result, expected_output);
       }

       #[test]
       fn test_parse_image_url_no_prefix_no_change() {
           let config = Config {
               variables: Variables {
                   ipfs_gateway: "https://ipfs.io/ipfs/".to_string(),
               },
           };
           let input_url = "examplehash";
           let expected_output = "examplehash";
           let result = parse_image_url(&config, input_url);
           assert_eq!(result, expected_output);
       }
   }
   ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Add tests for parse_image_url function"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by aurlic** [comment]
I would be happy to get to tackle down this issue ! I am curently learning Rust and Cairo and think that this would be a great fit for me to keep learning and developping my skills.

**Comment by Crosstons** [comment]
I can work on this, this would be my first contribution to this project  and I am curretly in my learning phase

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by 847850277** [comment]
I'd love to work on this! Can it be assigned to me

**Comment by emarc99** [comment]
Can I take this issue? Seems quite straight forward.
I have my development environment set up for testing here: https://emarc.hashnode.dev/starknet-development-with-docker-a-streamlined-setup-for-cairo-builders

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
  please /assign  this issue .
Thank You

**Comment by RajeshRk18** [comment]
I will take up this issue! I will add the tests, run them locally before pushing it.

ETA: 3 hours
