### ISSUE TITLE
Use profile pics within api.starknet.id.URI

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/api.starknet.id#31]

**Comment by Cevedale** [comment]
Here's a general example in Go:

go
Copy code
package main

import (
    "fmt"
    "io/ioutil"
    "log"
    "net/http"
)

func main() {
    // Replace this URL with the actual StarkNet API endpoint for profile pictures
    apiEndpoint := "http://api.starknet.id.uri/profile-picture/user123"

    // Make a GET request to the API endpoint
    response, err := http.Get(apiEndpoint)
    if err != nil {
        log.Fatal("Error making GET request:", err)
    }
    defer response.Body.Close()

    // Check if the request was successful (status code 200)
    if response.StatusCode == http.StatusOK {
        // Read the response body
        body, err := ioutil.ReadAll(response.Body)
        if err != nil {
            log.Fatal("Error reading response body:", err)
        }

        // Process the profile picture data as needed
        fmt.Println("Profile Picture Data:", string(body))
    } else {
        log.Fatal("API request failed with status code:", response.StatusCode)
    }
}
Make sure to replace the apiEndpoint with the actual URL you have for fetching profile pictures. Additionally, the structure of the API request and the response may vary depending on the StarkNet API documentation.
