### ISSUE TITLE
Refactor `get_renewal_data`

### ISSUE THREAD

**Issue by fricoben** [starknet-id/api.starknet.id#83]
## Description 

To have the STRK or ETH choice on the domain subscription, I’m trying to get the subscribed domains on a certain currency. Currently we have a query that gives a what domains are not subscribed. 

`get_renewal_data` already exists but I would like it to be for the address and not only focus on a domain.

**Comment by irisdv** [comment]
Closed by https://github.com/starknet-id/api.starknet.id/pull/84
