### ISSUE TITLE
Expiry not updating

### ISSUE THREAD

**Issue by fricoben** [starknet-id/api.starknet.id#99]
https://api.starknet.id/uri?id=421815956439 has an expiry on january 2027 when if you check on-chain you have April 2027 

This because the user [renewed](https://starkscan.co/tx/0x05d1282315b4f18c485ef3bd5355321d5f8c1f8728c9bb67a4e6eb5f8dd9102c) his domain for free but the indexer didn't catch. 

Note: I just understood that we used a different name for the free renewal function than last time. Might be the reason

**Comment by Marchand-Nicolas** [comment]
The indexer was late. This has been fixed
